# Analysis options for Cashense Flutter project
# Enforces high code quality standards for financial application

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_private_types_in_public_api: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/l10n/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    
    # Documentation
    public_member_api_docs: false  # Can be enabled later for public APIs
    
    # Error prevention
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_spread_collections: true
    
    # Security & Best practices for financial app
    avoid_dynamic_calls: true
    cast_nullable_to_non_nullable: true
    deprecated_member_use_from_same_package: true
    
    # Formatting
    curly_braces_in_flow_control_structures: true
    require_trailing_commas: true
