targets:
  $default:
    builders:
      json_serializable:
        options:
          # Creates a single .g.dart file for each .dart file with @JsonSerializable
          explicit_to_json: true
          include_if_null: false
          field_rename: snake