name: cashense
description: "AI-powered comprehensive financial management application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^2.6.1 
  
  # Firebase suite
  firebase_core: ^3.15.1 
  firebase_auth: ^5.6.2 
  cloud_firestore: ^5.6.11 
  firebase_storage: ^12.4.9
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_messaging: ^15.2.9
  cloud_functions: ^5.6.1
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.5.3
  
  # Navigation & UI
  go_router: ^16.0.0  
  
  # Localization & Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Utilities
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fl_chart: ^1.0.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  dynamic_color: ^1.7.0
  currency_picker: ^2.0.21
  money2: ^6.0.3
  dio: ^5.8.0+1
  # flutter_tts: ^4.2.3  # Temporarily disabled for Windows build
  equatable: ^2.0.7
  collection: ^1.19.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.13
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # Linting & Analysis
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
    - assets/data/
  
  # Generate localization files
  generate: true