// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ZTVmh3Yq-KFVRXODMi-ixh80DwikNHY',
    appId: '1:1030695688169:web:c6f650209ecbc063badd78',
    messagingSenderId: '1030695688169',
    projectId: 'cashense-prod',
    authDomain: 'cashense-prod.firebaseapp.com',
    storageBucket: 'cashense-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtt_ATaOqyXrVPxbJWZCJQwTfrNQ_sVlI',
    appId: '1:1030695688169:android:bc128c9e1f95ca6abadd78',
    messagingSenderId: '1030695688169',
    projectId: 'cashense-prod',
    storageBucket: 'cashense-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARHDhesx4DNsqllNFDJZ3jEfwHVHMuhY',
    appId: '1:1030695688169:ios:8e5648bf0709bcb3badd78',
    messagingSenderId: '1030695688169',
    projectId: 'cashense-prod',
    storageBucket: 'cashense-prod.firebasestorage.app',
    iosBundleId: 'com.cashense.cashense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDARHDhesx4DNsqllNFDJZ3jEfwHVHMuhY',
    appId: '1:1030695688169:ios:8e5648bf0709bcb3badd78',
    messagingSenderId: '1030695688169',
    projectId: 'cashense-prod',
    storageBucket: 'cashense-prod.firebasestorage.app',
    iosBundleId: 'com.cashense.cashense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ZTVmh3Yq-KFVRXODMi-ixh80DwikNHY',
    appId: '1:1030695688169:web:1e7088a014b65bdfbadd78',
    messagingSenderId: '1030695688169',
    projectId: 'cashense-prod',
    authDomain: 'cashense-prod.firebaseapp.com',
    storageBucket: 'cashense-prod.firebasestorage.app',
  );
}
