// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDduHtXit3WR_4f9KB7NZ0FBi-v-XKlIs',
    appId: '1:788140990788:web:342f061286177bdc993711',
    messagingSenderId: '788140990788',
    projectId: 'cashense-staging',
    authDomain: 'cashense-staging.firebaseapp.com',
    storageBucket: 'cashense-staging.firebasestorage.app',
    measurementId: 'G-9VXDZHRMED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeh2_2VlvQ6iMxkUnXiyxcy7urV0jCR3o',
    appId: '1:788140990788:android:bd7bd3d6a2e7d1c9993711',
    messagingSenderId: '788140990788',
    projectId: 'cashense-staging',
    storageBucket: 'cashense-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYyzB96oCo4HbimkKx2zJ70xSm70zrxVA',
    appId: '1:788140990788:ios:4e518c84c2763061993711',
    messagingSenderId: '788140990788',
    projectId: 'cashense-staging',
    storageBucket: 'cashense-staging.firebasestorage.app',
    iosBundleId: 'com.cashense.app.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYyzB96oCo4HbimkKx2zJ70xSm70zrxVA',
    appId: '1:788140990788:ios:4e518c84c2763061993711',
    messagingSenderId: '788140990788',
    projectId: 'cashense-staging',
    storageBucket: 'cashense-staging.firebasestorage.app',
    iosBundleId: 'com.cashense.app.staging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDduHtXit3WR_4f9KB7NZ0FBi-v-XKlIs',
    appId: '1:788140990788:web:92c35f28afb342e2993711',
    messagingSenderId: '788140990788',
    projectId: 'cashense-staging',
    authDomain: 'cashense-staging.firebaseapp.com',
    storageBucket: 'cashense-staging.firebasestorage.app',
    measurementId: 'G-Q6TMM0Q3M7',
  );
}
