// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOxcY6tTM5Bx8EffXmh-xpk__KEeRSvrQ',
    appId: '1:380247139382:web:e7b2c028ec5cbd984ca497',
    messagingSenderId: '380247139382',
    projectId: 'cashense-dev',
    authDomain: 'cashense-dev.firebaseapp.com',
    storageBucket: 'cashense-dev.firebasestorage.app',
    measurementId: 'G-8LM3MG9XN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzNRFcVcWG3-A8NldTz7LQGm-uoKK81A',
    appId: '1:380247139382:android:223e623a2ad4f3144ca497',
    messagingSenderId: '380247139382',
    projectId: 'cashense-dev',
    storageBucket: 'cashense-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWAckakwBQDccy5zwHDppUDzTt-KS0It0',
    appId: '1:380247139382:ios:eff94947608171e44ca497',
    messagingSenderId: '380247139382',
    projectId: 'cashense-dev',
    storageBucket: 'cashense-dev.firebasestorage.app',
    iosBundleId: 'com.cashense.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWAckakwBQDccy5zwHDppUDzTt-KS0It0',
    appId: '1:380247139382:ios:eff94947608171e44ca497',
    messagingSenderId: '380247139382',
    projectId: 'cashense-dev',
    storageBucket: 'cashense-dev.firebasestorage.app',
    iosBundleId: 'com.cashense.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOxcY6tTM5Bx8EffXmh-xpk__KEeRSvrQ',
    appId: '1:380247139382:web:65fbf3e168554e004ca497',
    messagingSenderId: '380247139382',
    projectId: 'cashense-dev',
    authDomain: 'cashense-dev.firebaseapp.com',
    storageBucket: 'cashense-dev.firebasestorage.app',
    measurementId: 'G-FJFWN2Q8CY',
  );
}
