name: cashense
description: "Cashense — a smart and secure personal expense tracker application, designed to revolutionize the way individuals manage, track, and optimize their finances."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.8


  # State management
  get: ^4.7.2  
  
  
  # Firebase suite
  firebase_core: ^4.0.0 
  firebase_auth: ^6.0.0 
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  
  # Local storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  drift: ^2.28.1
  
  # Navigation & UI
  go_router: ^16.0.0  
  
  # Localization & Internationalization
  easy_localization: ^3.0.8
  
  # Utilities
  # fl_chart: ^1.0.0
  # flutter_form_builder: ^10.1.0
  # form_builder_validators: ^11.2.0
  dynamic_color: ^1.7.0
  # currency_picker: ^2.0.21
  # money2: ^6.0.3
  # equatable: ^2.0.7
  # collection: ^1.19.1
  # uuid: ^4.5.1
  # path_provider: ^2.1.5
  # image_picker: ^1.1.2
  # cached_network_image: ^3.4.1
  # permission_handler: ^12.0.1
  # timezone: ^0.10.1
  device_preview: ^1.3.1
  dynamic_path_url_strategy: ^1.0.0
  dio: ^5.8.0+1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  haptic_feedback: ^0.5.1+1
  google_sign_in_all_platforms: ^1.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2 
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logos/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
    # Inter is the font family fallback
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: Icons
      fonts:
        - asset: assets/icons/Icons.ttf